# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftProjTemplate' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Alamofire'
    #pod 'RealmSwift'
    # Pods for swiftProjTemplate
    
    target 'swiftProjTemplateTests' do
        inherit! :search_paths
        # Pods for testing
        
    end
    
    target 'swiftProjTemplateUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
